name: PR Build Check

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - ready_for_review

permissions:
  pull-requests: read

jobs:
  ########### BUILD PACKAGE ############
  build-package:
    name: Build Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: PNPM Install
        uses: pnpm/action-setup@v3
        with:
          version: 8.15.6

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.10.0
          cache: 'pnpm'
          registry-url: https://registry.npmjs.org/

      - run: corepack enable

      - name: PNPM version
        run: pnpm -v

      - name: Install NPM Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Check
        if: ${{ always() }}
        run: pnpm build